spring.application.name=archive

spring.datasource.url=jdbc:postgresql://localhost:5432/storyloom
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mustache.null-value=

minio.url=http://127.0.0.1:9000
minio.access.key=${MINIO_ACCESS_KEY}
minio.secret.key=${MINIO_SECRET_KEY}
minio.bucket.name=storyloom-archive

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

server.servlet.session.timeout=30m

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:storyloom-keystore.p12
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
server.ssl.key-store-type=pkcs12
server.ssl.key-alias=storyloom